name:                AOC2017
version:             0.1.0.0
github:              "githubuser/AOC2017"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AOC2017#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- unordered-containers
- vector
- timeit
- comonad
- text
- timeit
- distributive
- pointedlist
- mtl
- array
- parsec
- semigroupoids
- parallel
- Stream
- MemoTrie
- Tape

library:
  source-dirs: src

executables:
  AOC2017-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fprof-auto
    - -O2
    dependencies:
    - AOC2017

tests:
  AOC2017-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AOC2017
