resolver: lts-18.6

packages:
- .
- ../../../../Hackage/Tape
- ../../../../Hackage/ComonadSheet
- ../../../../Hackage/PeanoWitnesses
- ../../../../Hackage/IndexedList
- ../../../../Hackage/NestedFunctor


extra-deps:
- Useful-0.0.6
- red-black-tree-0.1.0.0


#build:
  #library-profiling: true
  #executable-profiling: true
